apiVersion: v1
kind: ConfigMap
metadata:
  name: compat-matrix-config
  namespace: vmware-system-vdo
data:
  versionConfigURL: "https://raw.githubusercontent.com/asifdxtreme/Docs/master/sample/matrix/matrix.yaml"
  auto-upgrade: "disabled"
