# permissions for end users to view vdoconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vdoconfig-viewer-role
rules:
- apiGroups:
  - vdo.vmware.com
  resources:
  - vdoconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vdo.vmware.com
  resources:
  - vdoconfigs/status
  verbs:
  - get
