# permissions for end users to edit vspherecloudconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vspherecloudconfig-editor-role
rules:
- apiGroups:
  - vdo.vmware.com
  resources:
  - vspherecloudconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vdo.vmware.com
  resources:
  - vspherecloudconfigs/status
  verbs:
  - get
