apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: vspheredriveroperator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: VDOConfig is the Schema for the vdoconfigs API
      displayName: VDOConfig
      kind: VDOConfig
      name: vdoconfigs.vdo.vmware.com
      version: v1alpha1
    - description: VsphereCloudConfig is the Schema for the vspherecloudconfigs API
      displayName: Vsphere Cloud Config
      kind: VsphereCloudConfig
      name: vspherecloudconfigs.vdo.vmware.com
      version: v1alpha1
  description: vSphere Driver Operator a.k.a VDO attempts to Install/Configure/Manage
    the drivers required for running k8s on vSphere
  displayName: vSphere Driver Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - vdo
  - cpi
  - csi
  - cni
  links:
  - name: Vspheredriveroperator
    url: https://vspheredriveroperator.domain
  maturity: alpha
  provider:
    name: vmware
  version: 0.0.0
